---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package: name={{ docker_package }} state={{ docker_package_state }}

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes
#
# Werkt soms en soms niet.
#
#- name: "Wait for docker API port {{ docker_remote_port }}"
#  wait_for:
#    port: "{{ docker_remote_port }}"
#    delay: 10
#    state: present
#    timeout: 30

- include_tasks: docker-compose.yml
  when: docker_install_compose
