---
- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository.
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: Configure Docker Edge repo.
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}-edge'
    option: enabled
    value: '{{ docker_yum_repo_enable_edge }}'

- name: Configure Docker Test repo.
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}-test'
    option: enabled
    value: '{{ docker_yum_repo_enable_test }}'


- name: Override defaul docker systemctl
  file: path=/etc/systemd/system/docker.service.d state=directory

#- name: Copy docker (systemctl )override template
#  copy:
#    src: "{{ role_path }}/files/docker_systemctl"
#    dest: /etc/systemd/system/docker.service.d/override.conf
#    owner: root
#    group: root
#    mode: 0644
#  register: docker_systemctl

- name: Copy docker (systemctl )override template
  template:
    src: docker_systemctl.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  register: docker_systemctl



- name: Reload systemctl
  command: systemctl daemon-reload
  when: docker_systemctl.changed


