---
- name: create machine from template
  hosts: all
  gather_facts: false

  vars_prompt:
    - name: "vsphere_password"
      prompt: "vSphere Password"
    - name: "esxi_host"
      prompt: "ESXi host"
      private: no
      default: "172.16.60.100"
    - name: "notes"
      prompt: "VM notes"
      private: no
      default: "Deployed with ansible"

  roles:
     - deploy_vmware_guest
     #- other roles to execute directly inside VM after deployment

- name: Deploy docker-server
  hosts: all
  remote_user: ansible
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: true
  vars:
      pip_install_packages:
                  - name: docker
                    state: latest
  roles:
    - role: geerlingguy.repo-epel
    - role: geerlingguy.docker
    - role: geerlingguy.pip
  tasks:
      - include_tasks: tasks/portainer.yml
