---
- name: create machine from template
  hosts: all
  gather_facts: false

  vars_prompt:
    - name: "vsphere_password"
      prompt: "vSphere Password"
    - name: "esxi_host"
      prompt: "ESXi host"
      private: no
      default: "compute3.pxl.local"
    - name: "notes"
      prompt: "VM notes"
      private: no
      default: "Deployed with ansible"

  roles:
     - deploy_vmware_guest
     #- other roles to execute directly inside VM after deployment
     #- ...

- name: apply common configuration to all nodes
  hosts: all
  remote_user: ansible

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: ansible

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  remote_user: ansible

  roles:
    - db
