---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  package: name=ntp state=present
  become: yes
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  become: yes
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
#  service: name=ntp state=started enabled=yes # for ubuntu
  service: name=ntpd state=started enabled=yes # for Centos
  become: yes
  tags: ntp

# - name: Install python pip
#   package: name=python-pip state=present
#   become: yes
#   tags: pip

# - name: test to see if selinux is running
#   command: getenforce
#   register: sestatus
#   changed_when: false
#   become: yes
